### ISSUE TITLE
Music pauses on rotate in play menu

### ISSUE THREAD

**Issue by skipfie** [karimknaebel/phonograph-issue-tracker#218] opened 2017-05-01 14:57 UTC
Replicate:
Go into now playing while music is playing,
Rotate device
Music pauses

Device info:
---
<table>
<tr><td>App version</td><td>0.14.1</td></tr>
<tr><td>App version code</td><td>129</td></tr>
<tr><td>Android build version</td><td>004be2b338</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>lineage_helium-userdebug 7.1.1 NOF27B 004be2b338 test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>helium</td></tr>
<tr><td>Device model</td><td>Mi Max</td></tr>
<tr><td>Device product name</td><td>lineage_helium</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-10 15:20
Duplicate of #157

**Closed as completed by arkon** 2017-06-10 15:20 UTC
Labels: duplicate
