### ISSUE TITLE
I can't do anything with folder with 1000+ songs.

### ISSUE THREAD

**Issue by 4Lajf** [karimknaebel/phonograph-issue-tracker#263] opened 2018-10-14 15:25 UTC
I have a folder with 1000+ songs and phonograph pro. The problem is that I can't do anything with these files via "folders" tab. When I try to add all folder to the queue the app is not responding like nothing happend. Same for adding to playlist etc. Basically folders tab is now useless for me because I can only play songs one by one form there. I hope you get the point. How can I fix it? Will it be fixed in a future?
Also English is not my native language so sorry for grammar etc.

**Comment by arkon** [comment] 2019-01-27 22:33
Duplicate of https://github.com/kabouzeid/Phonograph/issues/594

**Closed as completed by arkon** 2019-01-27 22:33 UTC
