### ISSUE TITLE
Adding a song twice to playlist

### ISSUE THREAD

**Issue by nils-son** [karimknaebel/phonograph-issue-tracker#243] opened 2017-09-13 18:36 UTC
I would like a feature that if you try to add a song to a playlist where it's already part of, you get a notification and the possibility to decide if you want to add it although or not.

**Comment by arkon** [comment] 2017-09-13 19:17
Duplicate of https://github.com/kabouzeid/Phonograph/issues/109

**Closed as completed by arkon** 2017-09-13 19:17 UTC
Labels: duplicate
