### ISSUE TITLE
Songs in an album don't play in sequence 

### ISSUE THREAD

**Issue by r14balu** [karimknaebel/phonograph-issue-tracker#210] opened 2017-04-04 09:59 UTC
When I play the first song in an album, the songs following that will never play in the order in which they are meant to. They shuffle automatically. 
Please fix this issue.

**Comment by arkon** [comment] 2017-06-10 15:13
Are you in shuffle mode?

**Comment by arkon** [comment] 2017-08-08 02:33
Duplicate of #241.

**Closed as completed by arkon** 2017-08-08 02:33 UTC
Labels: duplicate
