### ISSUE TITLE
[request] Add marker

### ISSUE THREAD

**Issue by Lammaspaisti** [karimknaebel/phonograph-issue-tracker#240] opened 2017-07-30 10:57 UTC
I have many long music pieces (at least 40min.) and they have several movements in them. Adding a marker to jump to a certain movement within the same piece would be extremely helpful.

**Comment by arkon** [comment] 2017-09-01 12:44
Sort of a duplicate of https://github.com/kabouzeid/Phonograph/issues/177.

**Closed as completed by arkon** 2017-09-01 12:44 UTC
Labels: duplicate
