### ISSUE TITLE
Add Artist images manually

### ISSUE THREAD

**Issue by soumikbhatta** [karimknaebel/phonograph-issue-tracker#232] opened 2017-07-01 19:39 UTC
Please add a feature to add artist  images manually from gallery/file explorer.
Downloading artist images from app is very data consuming,which fails most of the times.  

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arkon** [comment] 2017-07-01 19:40
Duplicate of https://github.com/kabouzeid/Phonograph/issues/141

**Closed as completed by arkon** 2017-07-01 19:40 UTC
Labels: duplicate

**Comment by soumikbhatta** [comment] 2017-07-01 20:27
@arkon when are we going to get the feature

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by arkon** [comment] 2017-07-01 23:32
@Soumikbhatta I don't think this is a really high priority thing right now. Development depends on people's free time too, so there isn't any set timelines.
