### ISSUE TITLE
Suggestion: Support for various artists in an Album

### ISSUE THREAD

**Issue by mechamoelly** [karimknaebel/phonograph-issue-tracker#236] opened 2017-07-14 00:24 UTC
When various artists are on a single album (the artists are separated by a semicolon), all the artists cited are displayed together on the "artists" tab. It would be cool if they were displayed individually.

**Comment by arkon** [comment] 2017-07-14 00:52
Duplicate of https://github.com/kabouzeid/Phonograph/issues/151

**Closed as completed by arkon** 2017-07-14 00:52 UTC
Labels: duplicate
