### ISSUE TITLE
Folder blacklist

### ISSUE THREAD

**Issue by Randyslim76** [karimknaebel/phonograph-issue-tracker#183] opened 2017-01-14 23:59 UTC
I've got over 4gb of songs on my phone. Any new songs will not show up on my song list.  They will however show up in artists and albums.  Is there a song limit to the amount that will show in the song list?

Device info:
---
<table>
<tr><td>App version</td><td>0.13.5</td></tr>
<tr><td>App version code</td><td>124</td></tr>
<tr><td>Android build version</td><td>9</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MCG24.251-5</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>quark</td></tr>
<tr><td>Device model</td><td>XT1254</td></tr>
<tr><td>Device product name</td><td>quark_verizon</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-12 18:20
No, there's no limit. Does this still happen?

**Comment by Randyslim76** [comment] 2017-06-12 21:08
It has since been fixed.  Thank you.

I do have one request.  Can you add a feature to only scan certain folders
for music or at least have a "do not scan" for certain folders.  I have
sounds files from games, apps, and my work files popping up into the song
list.
Thank you again.  I use it daily.

**Comment by arkon** [comment] 2017-06-12 21:10
@Randyslim76 You should be able to add a `.nomedia` file to folders that you don't want scanned by Android's media store, which will prevent those files from popping up.

**Comment by Randyslim76** [comment] 2017-06-12 23:51
If I add the .nomedia file to those I won't be able to use my work files
when creating packs that include .wav .ogg and .acc files.
I use MX player for videos and it has the option to select only certain
folders to be scanned.

**Comment by arkon** [comment] 2017-06-12 23:53
@Randyslim76 Unfortunately, we make use of Android's built-in media store while MX Player implements their own. I'm not really sure what you mean by "creating packs" though.

**Comment by Randyslim76** [comment] 2017-06-13 02:12
Sorry "creating packs" is my work.  I use you're amazing player
constantly.  I have close to 1k songs playing constantly and when I am
working creating things on my phone (which contain music and sounds files)
your app will find them and throw them into the song list and it will stop
on each one.  I have to skip over each file just to get back to my music.
If I place a .nomedia in my work folders I won't be able to use my file
manager I use to build my packs(work) because of the .nomedia in the
folders.
Does that make more sense?

**Comment by arkon** [comment] 2017-06-13 02:24
Do you mean the `.nomedia` file will prevent you from being able to get to them in the file manager, or it'll just somehow be an issue with your workflow because of the extra file?

If it's the latter, `.nomedia` is recursive, meaning that subfolders within a folder with a `.nomedia` file won't be scanned either, so you can just have it in some parent folder, then folders within it can contain your work files?

**Comment by Randyslim76** [comment] 2017-06-13 03:59
When I make a video that contains multiple audio files..... Mainly .acc or
.wav files and I need to test the quality before I use them I use ES file
manager to select MX player to sample each file.  If I add a .nomedia to
the folder MX player won't see the files.  I then would have to rename the
.nomedia file to get access and sometimes I have to choose and reopen ES
just to see the sound files.

**Comment by Randyslim76** [comment] 2017-06-13 04:00
Sorry ....close and reopen.....

**Comment by arkon** [comment] 2017-06-13 14:43
I'll reopen this for now, but I'm not sure if we'll implement it anytime soon (or if ever).

**Comment by arkon** [comment] 2017-06-13 14:44
Actually, I'll close this again because it's a duplicate of #72 in that case. 😅

**Closed as completed by arkon** 2017-06-13 14:44 UTC
Labels: duplicate

**Comment by Randyslim76** [comment] 2017-06-13 14:54
If no one else has any complaints then don't fret about it for my issues
alone.
Is Phonograph is using Android media scanner?  Couldn't you add a default
search area location instead of letting it scan your whole drive?
If it's a issue then don't waste your time on it for me.  It's my problem
not yours.

I thank you for touching base with me.  Actually means a lot that you care
about the users.  I absolutely love Phonograph.  I am a huge fan of your
work.

**Comment by arkon** [comment] 2017-06-13 15:01
Yeah, Phonograph relies on the Android media store scanner, which is why it's a bit of a pain to handle these sort of cases. Ideally, we'd be able to make it work though.

No problem about touching base. The app is actually built by @kabouzeid and I've only recently started trying to contribute to it, so I took the time to triage all the issues here.

**Comment by Randyslim76** [comment] 2017-06-13 15:50
Thanks mate! I appreciate you looking into it.  Like I said it's my problem
so don't stress.
