### ISSUE TITLE
Album year is 0

### ISSUE THREAD

**Issue by Dash3k** [karimknaebel/phonograph-issue-tracker#238] opened 2017-07-24 13:37 UTC
On some albums it says it is year 0.Checked song and album tags and everything seems fine but the album year still shows as 0. I can provide screenshots via email.

**Comment by arkon** [comment] 2017-07-24 13:38
Duplicate of https://github.com/kabouzeid/Phonograph/issues/121

**Closed as completed by arkon** 2017-07-24 13:38 UTC
Labels: duplicate
