### ISSUE TITLE
Phonograph can't read songs

### ISSUE THREAD

**Issue by alejandro-rios** [karimknaebel/phonograph-issue-tracker#258] opened 2018-02-05 13:32 UTC
Hi, i have a OnePlus 5T and i send some music files using Airdroid and TeamViewer Quicksupport, the file are ok(on the file manager), but Phonograph doesn't fin it.

**Comment by Simmons572** [comment] 2018-02-11 16:34
Hi, I would like to add to this:
I have a Galaxy S8, and I keep getting a "couldn't play this song" error. Also, all of my playlists are now blank.

**Comment by arkon** [comment] 2019-01-27 22:44
Duplicate of other issues.

**Closed as completed by arkon** 2019-01-27 22:44 UTC
