### ISSUE TITLE
Default notification unreadable (white on white)

### ISSUE THREAD

**Issue by corcorac** [karimknaebel/phonograph-issue-tracker#97] opened 2016-06-29 01:15 UTC
Music with no album art is displayed as white text on a white background and thus unreadable. If I turn colored notification off it fixes it till the next song and then I have to turn colored notification back on to fix it till the next song.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>G935TUVS3APD8</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G935TUVS3APD8</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2qltetmo</td></tr>
<tr><td>Device model</td><td>SM-G935T</td></tr>
<tr><td>Device product name</td><td>hero2qltetmo</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-12 23:44
Sort of a duplicate of #17.

**Closed as completed by arkon** 2017-06-12 23:44 UTC
Labels: duplicate
