### ISSUE TITLE
Edit lables

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#89] opened 2016-06-22 11:54 UTC
Love your app! I'm having some problems when editing lables since the last update. If I change the title of an album the changes will not show, but when I try it again it does for some reason.
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>10e8b0a574</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>cm_hlte-userdebug 5.1.1 LMY49J 10e8b0a574 test-keys</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hltexx</td></tr>
<tr><td>Device model</td><td>SM-N9005</td></tr>
<tr><td>Device product name</td><td>cm_hlte</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-10 15:59
Duplicate of #26 (probably).

**Closed as completed by arkon** 2017-06-10 15:59 UTC
Labels: duplicate
