### ISSUE TITLE
[Suggestion] Sort by 'album artist' instead of 'artist'

### ISSUE THREAD

**Issue by tysox** [karimknaebel/phonograph-issue-tracker#247] opened 2017-09-16 12:07 UTC
The 'Artist' tab should sort by Album Artist instead of Track Artist. This would prevent albums with multiple artists (such as musicals) or collaborations (i.e. "Artist A" feat. "Artist B") being split across multiple artists.

**Comment by arkon** [comment] 2017-09-16 15:42
Duplicate of https://github.com/kabouzeid/Phonograph/issues/146

**Closed as completed by arkon** 2017-09-16 15:42 UTC
Labels: duplicate
