### ISSUE TITLE
First song's artist tag is displayed on album overview instead of the 'Album artist' tag

### ISSUE THREAD

**Issue by elmkzgirxp** [karimknaebel/phonograph-issue-tracker#224] opened 2017-06-11 16:21 UTC
When there are different artists in an album, the album artist does not appear on album overview but instead the first song's artist.

**Comment by arkon** [comment] 2017-06-11 16:30
Duplicate of https://github.com/kabouzeid/Phonograph/issues/146.

**Closed as completed by arkon** 2017-06-11 16:30 UTC
Labels: duplicate
