### ISSUE TITLE
Shuffle albums

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#75] opened 2016-06-08 12:11 UTC
On the TITLE-Tab, where all songs from the library are displayed, there is this nice "Random Playback" button, an easy way to start random playback all around the user's music collection.

I would love the same feature for the ALBUMS-Tab. Which just starts playing any random album from the library.

**Comment by arkon** [comment] 2017-06-10 20:01
As suggested in #132, it should just shuffle albums as their wholes.

**Comment by arkon** [comment] 2019-01-27 22:35
Duplicate of https://github.com/kabouzeid/Phonograph/issues/439

**Closed as completed by arkon** 2019-01-27 22:35 UTC
Labels: enhancement
