### ISSUE TITLE
Status Bar dynamic compatibality  (such as Essential Phone)

### ISSUE THREAD

**Issue by ghost** [karimknaebel/phonograph-issue-tracker#255] opened 2017-11-18 21:42 UTC
So I recently just got an Essential Phone and have been looking into app support of the camera cutout. Without support the cutout is dorky as I speculated, but if the software supports it then it's really a non-issue, fortunately. Since I spend most my time on my phone using the music player I was looking into this I found this thread by an Essential Dev that they have requested users redirect them to for this exact topic.

https://www.reddit.com/r/essential/comments/7amvxr/app_compatibility_with_camera_cutout_in_essential/

To clarify, this wouldn't be a special change that only benefits Essential devices, but is instead is utilizing "standard android APIs correctly and not asking anything specific for Essential phone.". Thought I'd post here in hopes of seeing these improvements being made!

**Comment by arkon** [comment] 2017-11-19 16:57
This is definitely on the radar, thanks!

Duplicate of https://github.com/kabouzeid/Phonograph/issues/197

**Closed as completed by arkon** 2017-11-19 16:57 UTC
Labels: duplicate
