### ISSUE TITLE
Audio randomly stopping at the middle of some songs

### ISSUE THREAD

**Issue by DigitalGhostt** [karimknaebel/phonograph-issue-tracker#250] opened 2017-10-04 11:07 UTC
While audio stops the player still thinks the audio is still playing as the notification icon doesn't change not the moving progress bar on the app

Nexus 5x Android 8.0.0

**Comment by arkon** [comment] 2017-10-04 14:46
Duplicate of https://github.com/kabouzeid/Phonograph/issues/245

**Closed as completed by arkon** 2017-10-04 14:46 UTC
Labels: duplicate
