### ISSUE TITLE
Cant change artist art

### ISSUE THREAD

**Issue by MakoriSM** [karimknaebel/phonograph-issue-tracker#80] opened 2016-06-11 02:12 UTC
The automatic artist detection works 90% of the time but whenever it gets it wrong i have no way if changing the art. This is probably my only complaint because the app is nice except for this 1 feature which im confused about why it wasnt implemented earliet
## 
## Device info:

<table>
<tr><td>App version</td><td>0.13.0</td></tr>
<tr><td>App version code</td><td>115</td></tr>
<tr><td>Android build version</td><td>34</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MPI24.65-33</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>osprey_umts</td></tr>
<tr><td>Device model</td><td>MotoG3</td></tr>
<tr><td>Device product name</td><td>osprey_retgb</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-10 15:50
Duplicate of #79.

**Closed as completed by arkon** 2017-06-10 15:50 UTC
Labels: duplicate
