### ISSUE TITLE
Delete Songs in Queue with swiping

### ISSUE THREAD

**Issue by christophsanz** [karimknaebel/phonograph-issue-tracker#147] opened 2016-09-08 16:34 UTC
It would be nice to delete songs from the Queue by swiping rather than klicking on the songs menu everytime.

A big "+" next to each song in your library to add them to your current queue would also improve the experience.
## Device info:

<table>
<tr><td>App version</td><td>0.13.1</td></tr>
<tr><td>App version code</td><td>117</td></tr>
<tr><td>Android build version</td><td>5ffc70a1ef</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>bacon-userdebug 6.0.1 MOB30Z 5ffc70a1ef test-keys</td></tr>
<tr><td>Device brand</td><td>oneplus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>A0001</td></tr>
<tr><td>Device model</td><td>A0001</td></tr>
<tr><td>Device product name</td><td>bacon</td></tr>
<tr><td>Device hardware name</td><td>bacon</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-10 15:07
Duplicate of https://github.com/kabouzeid/Phonograph/issues/77

**Closed as completed by arkon** 2017-06-10 15:07 UTC
Labels: duplicate
