### ISSUE TITLE
Sorting Music by Genre.

### ISSUE THREAD

**Issue by Klawzy** [karimknaebel/phonograph-issue-tracker#189] opened 2017-02-12 14:10 UTC
I would love to see this already amazing player have an option in library to sort music by genre. At the moment I need to create playlist and sort music by myself. I will absolutely donate if you guys make it into reality.

**Comment by trinadyerra264** [comment] 2017-04-13 18:26
Please add this feature.

**Comment by arkon** [comment] 2017-06-10 14:48
Duplicate of #111

**Closed as completed by arkon** 2017-06-10 14:48 UTC
Labels: duplicate
