### ISSUE TITLE
Custom artist images

### ISSUE THREAD

**Issue by paulheising** [karimknaebel/phonograph-issue-tracker#79] opened 2016-06-10 15:38 UTC
When I turn off the option "Automatically download artist images", because I actually want to use the images, which I added to my music library using *.jpg files stored in the artist-directories, no images are found at all, even when I let phonograph update the artist image (it says "Error" via Toast message).

For example, let the artist be "Shinedown", and I wanted to use the Shinedown Logo as the artist image, so my folder structure is:

\Music\Shinedown\

This is where the subdirectories for the albums are placed. And this is also where my desired artist image is placed. I tried the following namings:

cover.jpg
artist.jpg
Shinedown.jpg

None of them has been recognized by Phonograph, so I guess there is currently no way to use custom artist images, is there?

It would be nice, if Phonograph could be searching for artist images in the library, either if no image is found online, or the option to download them is turned off.

**Comment by arkon** [comment] 2017-06-10 15:53
Duplicate of https://github.com/kabouzeid/Phonograph/issues/141

**Closed as completed by arkon** 2017-06-10 15:53 UTC
Labels: duplicate
