### ISSUE TITLE
Artist Pictures and Album details not updating 

### ISSUE THREAD

**Issue by sterkaart** [karimknaebel/phonograph-issue-tracker#221] opened 2017-05-19 16:25 UTC
Whenever I try to edit albums details, it shows me that I have done it but I don't see any changes in the library. I think it's because there isn't a save button in my version so I have to go back thinking that I've saved it, but it doesn't happen. Also, whenever I try to update the artist photo, it gives me an error message. Last.fm does not work well with other apps so it would be nice to give users an option to upload their own artist images from their SD card instead of just relying on last.fm. Also, the report section crashes so I posted this from the website. Otherwise, it's a promising app and I have high hopes for it. Thanks xx
Device info:
---
<table>
<tr><td>App version</td><td>0.15.0</td></tr>
<tr><td>App version code</td><td>132</td></tr>
<tr><td>Android build version</td><td>J710FXXU2AQC3</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.J710FXXU2AQC3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j7xelte</td></tr>
<tr><td>Device model</td><td>SM-J710F</td></tr>
<tr><td>Device product name</td><td>j7xeltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7870</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by arkon** [comment] 2017-06-10 16:10
Duplicate of #26 for the tagging stuff.

**Closed as completed by arkon** 2017-06-10 16:10 UTC
Labels: duplicate
