### ISSUE TITLE
Android Auto support

### ISSUE THREAD

**Issue by sal0max** [karimknaebel/phonograph-issue-tracker#96] opened 2016-06-26 10:55 UTC
Phonograph is the one and only app I use to listen to music on all my devices. Now that I soon own a car with a Android Auto supported radio, it would be awesome if Phonograph could be used there, too. I decompiled the Manifest and guess the app has not yet built in support for it.

According to [the guidelines](https://developer.android.com/training/auto/audio/index.html), these are the obligatory features an app must include, to be available for Android Auto:
1. [Build a service](https://developer.android.com/training/auto/audio/index.html#implement_browser) that provides audio track listing information. It must extend `MediaBrowserService`. There is also a [sample project](https://developer.android.com/samples/MediaBrowserService/index.html).
2. [Configure the app manifest](https://developer.android.com/training/auto/audio/index.html#config_manifest):
   1. Declare that the app supports Android Auto.
   2. Declare the implemented media browser service, which provides a browsable list of the audio tracks.
   3. Specify a notification icon.
3. [Register a `MediaSession` object](https://developer.android.com/training/auto/audio/index.html#implement_callback) and implement the `MediaSession.Callback` object to enable playback controls.

Additionally, you could provide a different layout when used in Android Auto. There are [layout guidelines](https://www.google.com/design/spec-auto/audio-apps/audio-app-anatomy.html). The layout can be swapped when detecting that the phone [is connected to Android Auto](https://developer.android.com/training/auto/audio/index.html#isconnected).

**Comment by arkon** [comment] 2017-06-10 14:54
Duplicate of https://github.com/kabouzeid/Phonograph/issues/79

Thanks for the detailed post though!

**Closed as completed by arkon** 2017-06-10 14:54 UTC
Labels: duplicate
